'use strict'

/**
 * shared/pubspec.js
 *
 * Generates the server-controlled pubspec.yaml written to every exam workspace.
 *
 * Purpose:
 *   Students must not be able to alter dependency versions, sources, build hooks,
 *   Flutter/Dart SDK constraints, or the build target. This module is the single
 *   source of truth for what is allowed in the exam environment.
 *
 * The student-provided pubspec.yaml (if any) is IGNORED — the worker always
 * overwrites it with the output of generatePubspec().
 *
 * Changing the allowlist requires:
 *   1. Update APPROVED_PACKAGES below
 *   2. Update sandbox/packages/pubspec.yaml (same list)
 *   3. Rebuild the sandbox Docker image (docker build ./sandbox)
 *   4. Bump EXAM_ENV_VERSION if the change is incompatible with cached results
 */

const EXAM_ENV_VERSION  = process.env.EXAM_ENV_VERSION   || 'v1'
const FLUTTER_CONSTRAINT = process.env.FLUTTER_CONSTRAINT || '>=3.22.0 <4.0.0'
const DART_CONSTRAINT    = process.env.DART_CONSTRAINT    || '>=3.4.0 <4.0.0'

/**
 * Approved packages for exam projects.
 *
 * Key  = package name
 * Value = version constraint string, or { sdk: 'flutter' } for Flutter SDK packages
 *
 * These MUST match what is pre-seeded in the sandbox image.
 * Do NOT add packages without also updating sandbox/packages/pubspec.yaml
 * and rebuilding the image.
 */
const APPROVED_PACKAGES = {
  // Flutter SDK — always present, no version constraint needed
  flutter:        { sdk: 'flutter' },

  // Approved exam dependencies — must also be pre-seeded in the sandbox image
  provider:             '^6.1.2',
  go_router:            '^14.2.7',
  flutter_bloc:         '^8.1.6',
  equatable:            '^2.0.5',
  http:                 '^1.2.1',
  intl:                 '^0.19.0',
  shared_preferences:   '^2.3.1',
  collection:           '^1.18.0',
}

const APPROVED_DEV_PACKAGES = {
  // flutter_test belongs in dev_dependencies (test framework, not a runtime dep)
  flutter_test:   { sdk: 'flutter' },
  flutter_lints:  '^4.0.0',
}

/**
 * Generates the server-controlled pubspec.yaml content.
 *
 * @param {string} [projectName='exam_project'] - The dart package name (must be snake_case)
 * @returns {string} YAML string to write to /workspace/pubspec.yaml
 */
function generatePubspec(projectName = 'exam_project') {
  const lines = [
    `# AUTO-GENERATED by exam compiler service — DO NOT EDIT`,
    `# Exam environment version: ${EXAM_ENV_VERSION}`,
    `# Any student-provided pubspec.yaml is replaced by this file.`,
    ``,
    `name: ${sanitizePackageName(projectName)}`,
    `description: Exam submission project`,
    `publish_to: 'none'`,
    ``,
    `environment:`,
    `  sdk: '${DART_CONSTRAINT}'`,
    `  flutter: '${FLUTTER_CONSTRAINT}'`,
    ``,
    `dependencies:`,
  ]

  // SDK packages first
  for (const [name, spec] of Object.entries(APPROVED_PACKAGES)) {
    if (typeof spec === 'object' && spec.sdk) {
      lines.push(`  ${name}:`)
      lines.push(`    sdk: ${spec.sdk}`)
    }
  }
  // Versioned packages
  for (const [name, spec] of Object.entries(APPROVED_PACKAGES)) {
    if (typeof spec === 'string') {
      lines.push(`  ${name}: ${spec}`)
    }
  }

  lines.push(``)
  lines.push(`dev_dependencies:`)

  for (const [name, spec] of Object.entries(APPROVED_DEV_PACKAGES)) {
    if (typeof spec === 'object' && spec.sdk) {
      lines.push(`  ${name}:`)
      lines.push(`    sdk: ${spec.sdk}`)
    } else {
      lines.push(`  ${name}: ${spec}`)
    }
  }

  lines.push(``)
  lines.push(`flutter:`)
  lines.push(`  uses-material-design: true`)
  lines.push(``)

  return lines.join('\n')
}

/** Sanitise an arbitrary string into a valid Dart package name (snake_case, no hyphens). */
function sanitizePackageName(name) {
  return (name || 'exam_project')
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, '_')
    .replace(/^[0-9]/, '_')
    .slice(0, 64) || 'exam_project'
}

/**
 * Generates the server-controlled analysis_options.yaml content.
 *
 * Every Flutter project needs this file to activate flutter_lints and ensure
 * consistent analysis behaviour. Without it, flutter_lints (listed in
 * dev_dependencies) has no effect, and flutter analyze may exit non-zero
 * due to missing configuration.
 *
 * Students cannot override this — the worker always writes it to the workspace.
 *
 * @returns {string} YAML string to write to /workspace/analysis_options.yaml
 */
function generateAnalysisOptions() {
  return [
    `# AUTO-GENERATED by exam compiler service — DO NOT EDIT`,
    ``,
    `include: package:flutter_lints/flutter.yaml`,
    ``,
    `analyzer:`,
    `  errors:`,
    `    # Treat these as warnings only, not errors that cause non-zero exit`,
    `    unnecessary_dev_dependency: warning`,
    ``,
  ].join('\n')
}

module.exports = { generatePubspec, generateAnalysisOptions, EXAM_ENV_VERSION, APPROVED_PACKAGES, DART_CONSTRAINT, FLUTTER_CONSTRAINT }
